// THE GLYPH LEDGER, guarded (owner's ballot, moonglade-internal/design/glyphs/README.md,
// 2026-09-05). Seven Unicode stand-ins became drawn icons and six became different
// characters; the mark-pick buttons became the marks. These are source guards -- they read
// the component files, so a later edit cannot quietly put an old glyph back.
//
// Each swap is asserted BOTH ways: the new mark present at the site, the old one gone from
// the file. A one-way assertion would pass while a duplicate old row sat beside the new.
//
// The ballot, for anyone reading this in a year:
//   icons  N uses · USER LORA · Entered · Snippets · search (all surfaces) · Folio · Panel
//   chars  ✧->✎ Edit this · ▤->⎙ Print sheet · ★->♛ membership · ★->⚔ Arena ·
//          ★->❖ skin flag (⚑ banner kept) · ↺->↩ undo (see G12: the ballot
//          said ⎌, which does not render as undo in this font stack; Remix keeps ↺)
//   G2     the Branding mark buttons render the mark's own image
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(here, "..", "..", "gallery", "src");
// Line endings normalised. .gitattributes pins LF in the REPO, but a Windows checkout has
// CRLF in the working tree -- and these files are read off the working tree, so a pattern
// with a newline in it would match on one machine and not the other.
const src = (rel) => readFileSync(path.join(SRC, rel), "utf8").split("\r\n").join("\n");

const app = src("App.jsx");
const modelPicker = src("components/ModelPicker.jsx");
const myArt = src("components/MyArtOverlay.jsx");
const contestConfirm = src("components/ContestConfirm.jsx");
const contestsOverlay = src("components/ContestsOverlay.jsx");
const contestDetail = src("components/ContestDetail.jsx");
const contestDetailMobile = src("components/ContestDetailMobile.jsx");
const contestsMobile = src("components/ContestsMobile.jsx");
const drawer = src("components/GenerateDrawer.jsx");
const filters = src("components/FiltersPanel.jsx");
const palette = src("components/CommandPalette.jsx");
const galleryMobile = src("components/GalleryMobile.jsx");
const aiTools = src("components/AiToolsModal.jsx");
const dupOverlay = src("components/DuplicateReviewOverlay.jsx");
const dupMobile = src("components/DuplicateReviewMobile.jsx");
const folio = src("components/FolioOverlay.jsx");
const appMobile = src("components/AppMobile.jsx");
const tabBar = src("components/TabBarMobile.jsx");
const details = src("components/DetailsView.jsx");
const actions = src("components/ActionsMenu.jsx");
const enhance = src("components/EnhanceTab.jsx");
const publish = src("components/PublishOverlay.jsx");
const panel = src("components/ControlPanelOverlay.jsx");
const controlMobile = src("components/ControlMobile.jsx");
const icons = src("icons/Icons.jsx");
const iconCss = src("styles/icons.css");
const dockCss = src("styles/dock.css");

// ---------------------------------------------------------------- the icon module

test("the icon module carries all seven picks, drawn in currentColor, fetched at no point", () => {
  for (const name of ["search", "uses", "lora", "entered", "snippets", "folio", "panel"]) {
    assert.match(icons, new RegExp("\\n  " + name + ": \\("), "missing icon: " + name);
  }
  // currentColor is the whole tinting mechanism: a literal hex here means one icon has
  // stopped following its skin.
  assert.doesNotMatch(icons, /#[0-9A-Fa-f]{6}/, "an icon still carries a hardcoded colour");
  assert.match(icons, /fill="currentColor"/);
  // no runtime load of any kind -- these are elements in the bundle
  assert.doesNotMatch(icons, /fetch\(|new Image\(|<img|url\(|\.svg"/);
  assert.match(icons, /GENERATED by tools\/build_icons\.py/);
  assert.match(icons, /size = "1em"/);           // type-relative by default
});

test("the licence ships beside the art", () => {
  const notice = readFileSync(path.join(SRC, "icons", "NOTICE"), "utf8");
  assert.match(notice, /glyphs\.fyi/);
  assert.match(notice, /github\.com\/gorango\/glyphs/);
  assert.match(notice, /MIT License/);
  assert.match(notice, /THE SOFTWARE IS PROVIDED "AS IS"/);
  // and the .svg files it covers are actually here
  const svgs = readdirSync(path.join(SRC, "icons")).filter((f) => f.endsWith(".svg"));
  assert.equal(svgs.length, 7, "expected the seven assigned .svg files: " + svgs.join(", "));
});

test("the duo hairlines survive at icon sizes; a drawn stroke-width is left alone", () => {
  // The art is 80x80 with a default stroke-width of 1. At 10px that is a fifth of a pixel.
  const duo = src("icons/check-badge_duo.svg");
  assert.match(duo, /vector-effect="non-scaling-stroke"/);
  // person-private draws its own weight; pinning THAT to 6 device px would swallow the icon
  const bold = src("icons/person-private_bold.svg");
  assert.match(bold, /stroke-width="6"/);
  assert.doesNotMatch(bold, /vector-effect/);
});

// ---------------------------------------------------------------- 1-7, the drawn icons

test("1. the model picker's uses count wears the drawn icon, not the Similar diamond", () => {
  assert.match(modelPicker, /<Icon name="uses" \/> \{fmtCompact\(p\.ref_count\)\} uses/);
  assert.doesNotMatch(modelPicker, /◈/);
});

test("2. My Art's USER LORA badge wears the palette", () => {
  assert.match(myArt, /<Icon name="lora" \/>USER LORA/);
  assert.doesNotMatch(myArt, /◈/);
});

test("3. every Entered badge wears the check-badge -- one meaning, one icon", () => {
  for (const [name, file] of [
    ["ContestConfirm", contestConfirm], ["ContestsOverlay", contestsOverlay],
    ["ContestDetail", contestDetail], ["ContestDetailMobile", contestDetailMobile],
    ["ContestsMobile", contestsMobile],
  ]) {
    assert.match(file, /<Icon name="entered" \/>[Ee]ntered/, name + " lost the Entered icon");
    assert.doesNotMatch(file, /★ ?[Ee]ntered/, name + " still has a ★ Entered");
  }
  // the phone list said it in a built string, so it had to become real markup
  assert.match(contestsMobile, /className="cmb-entered-inline"/);
  assert.match(iconCss, /\.cmb-entered-inline \.mgico/);
});

test("4. the composer's Snippets toggle wears the quote mark", () => {
  assert.match(drawer, /<Icon name="snippets" \/>Snippets<\/button>/);
  assert.doesNotMatch(drawer, /★ Snippets<\/button>/);
});

test("5. EVERY search surface wears the binoculars (owner: \"All search surfaces\")", () => {
  const surfaces = [
    ["desktop library bar", filters, /className="mgl-sglyph"[\s\S]{0,90}?<Icon name="search" \/><\/i>/],
    ["command palette field", palette, /className="mgpal-sglyph"[\s\S]{0,60}?<Icon name="search" \/><\/span>/],
    ["the phone's field", galleryMobile, /className="glm-search-icon"[\s\S]{0,90}?<Icon name="search" \/><\/span>/],
    ["AI Tools", aiTools, /aria-hidden="true">\s*<Icon name="search" \/>/],
    ["Duplicate Review", dupOverlay, /className="mgdr-search-icon"[\s\S]{0,60}?<Icon name="search" \/><\/span>/],
    ["the Folio's record search", folio, /className="mgfo-search-ic">\s*<Icon name="search" \/>/],
    ["the palette's Jump to Search row", app, /icon: <Icon name="search" \/>, label: "Jump to Search"/],
  ];
  for (const [label, file, re] of surfaces) assert.match(file, re, label + " is not wearing it");
  // and no search glyph is left anywhere
  for (const [label, file] of [["FiltersPanel", filters], ["CommandPalette", palette],
    ["GalleryMobile", galleryMobile], ["AiToolsModal", aiTools],
    ["DuplicateReviewOverlay", dupOverlay], ["FolioOverlay", folio], ["App", app]]) {
    assert.doesNotMatch(file, /⌕/, label + " still has a ⌕");
  }
  assert.doesNotMatch(galleryMobile, /⚲/, "the phone's search still has a ⚲");
});

test("5b. the desktop Filters pill KEEPS its ⚲ -- it is filters, not search", () => {
  assert.match(filters, /<span>⚲ Filters\{/);
});

test("6. the phone's Folio button wears the trophy", () => {
  assert.match(appMobile, /glm-iconbtn-gold[\s\S]{0,140}<Icon name="folio" \/><\/button>/);
  assert.doesNotMatch(appMobile, /onClick=\{openFolio\}>🌙</);
});

test("7. BOTH of the Control Panel's doors wear the laptop-cog", () => {
  assert.match(tabBar, /key: "control", icon: <Icon name="panel" \/>/);
  assert.match(app, /go\("goto\.panel", <Icon name="panel" \/>/);
  assert.doesNotMatch(app, /⛭/);
  assert.doesNotMatch(tabBar, /icon: "⚙"/);
  // CreateMobile's "⚙ Advanced" is generic settings, NOT the Panel -- it keeps its gear
  assert.match(src("components/CreateMobile.jsx"), /⚙ Advanced/);
});

// ---------------------------------------------------------------- the character picks

test("G5: the record's Edit this wears ✎ -- the same mark the palette's Edit row uses", () => {
  assert.match(details, /✎ Edit this<\/button>/);
  assert.doesNotMatch(details, /✧ Edit this/);
  assert.match(app, /img\("edit", "✎", "Edit"/);        // the mark it is matching
});

test("G6: Print sheet wears ⎙ (one item -- the phone's contact sheet rides the same menu)", () => {
  assert.match(actions, /item\("⎙ Print sheet", printSheet\)/);
  assert.doesNotMatch(actions, /▤ Print sheet/);
});

test("G9: the membership gate is a crown, in PixAI purple that no skin retints", () => {
  assert.match(enhance, /className="mgdock-aigate" title="Membership required">♛</);
  assert.doesNotMatch(enhance, /mgdock-aigate[^>]*>★/);
  // --purple-bright is the app's only :root-fixed violet; --lavender/--mauve go peach
  // under ember and mint under verdant, which would stop a PixAI fact being PixAI's colour.
  const rule = dockCss.slice(dockCss.indexOf(".mgdock-aigate {"));
  const block = rule.slice(0, rule.indexOf("}") + 1);
  assert.match(block, /color: color-mix\(in oklab, var\(--purple-bright\)/);
  assert.match(block, /border: 1px solid color-mix\(in oklab, var\(--purple-bright\)/);
  assert.doesNotMatch(block, /--gold/);
});

test("G10: the Arena note wears crossed swords", () => {
  assert.match(publish, /className="mgpub-cttrack">⚔ counts toward The Arena/);
  assert.doesNotMatch(publish, /★ counts toward/);
});

test("G11: the Folio's reward flags are ❖ skin + ⚑ banner (the owner's pick B)", () => {
  assert.match(folio, /className="mgfo-flag">❖ unlocks \{skinName\} skin/);
  assert.match(folio, /className="mgfo-flag">⚑ unlocks a banner/);   // the banner keeps its flag
  assert.doesNotMatch(folio, /★ unlocks/);
});

/* G12 -- the owner picked ⎌ (UNDO SYMBOL) and it does not survive contact with the
   app's font stack: measured in driven Chromium, U+238C falls through Segoe UI Symbol to
   a fallback that draws an arch on two circles (and, at some sizes, a boxed placeholder).
   It is not tofu, so a width check passes it -- it simply does not read as undo, at any
   size. ↩ LEFTWARDS ARROW WITH HOOK is the nearest sane neighbour: the same shape
   U+238C is NAMED for, drawn as text (not emoji) in both the system and mono stacks,
   distinct from Remix's ↺ and from Sync's ⟳. Flagged to the owner on the branch. */
test("G12: undo is ↩ at the undo sites -- and Remix still turns back with ↺", () => {
  assert.match(dupOverlay, /"↩ Undo"/);
  assert.match(dupMobile, /"↩ Undo"/);                 // the phone twin of the same button
  assert.match(drawer, /↩ Undo delete<\/button>/);
  assert.match(panel, /↩ Reset crop/);
  for (const [label, file] of [["DuplicateReviewOverlay", dupOverlay],
    ["DuplicateReviewMobile", dupMobile]]) {
    assert.doesNotMatch(file, /↺ Undo/, label + " still has a ↺ Undo");
  }
  assert.doesNotMatch(drawer, /↺ Undo delete/);
  assert.doesNotMatch(panel, /↺ Reset crop/);
  // Remix is a different verb and keeps the arrow (G13 kept ⟳ for Sync the same way)
  assert.match(details, /↺ Remix<\/button>/);
  assert.match(src("components/GridContextMenu.jsx"), /\["↺", "Remix"/);
  // and the credit ledger's "refunded" arrow is a receipt, not an action
  assert.match(src("components/AccountSubOverlay.jsx"), /↺ refunded/);
});

test("G4/G13: the settled marks are untouched -- Hero ▣, Sync ⟳", () => {
  assert.match(src("components/SeparatorBar.jsx"), /\["hero", "▣"/);
  assert.match(app, /icon: "⟳", label: "Sync now"/);
});

// ---------------------------------------------------------------- G2, and the one meaning

test("G2: every mark button renders the mark's own image, and falls back honestly", () => {
  // one component, four mounts (two rows + the live sample on desktop, the phone's card)
  assert.match(panel, /export function MarkArt\(\{ mark \}\)/);
  assert.match(panel, /if \(!url \|\| broken\) return <span className="mgcp-marknoart"/);
  assert.match(panel, /onError=\{\(\) => setBroken\(true\)\}/);
  assert.equal((panel.match(/<MarkArt mark=/g) || []).length, 3);
  assert.match(controlMobile, /<MarkArt mark=\{m\} \/>/);
  assert.match(controlMobile, /MarkArt[\s\S]{0,40}from "\.\/ControlPanelOverlay\.jsx"/);  // imported, not re-forked
  // the old failures, both gone: the stand-in glyph, and the handler that emptied the button
  assert.doesNotMatch(panel, /e\.currentTarget\.remove\(\)[\s\S]{0,80}m\.id === "logo"/);
  assert.doesNotMatch(panel, /m\.id === "logo" \? "🌙"/);
  assert.doesNotMatch(controlMobile, /m\.id === "logo" \? "🌙"/);
  // an empty tile is drawn, not left blank
  assert.match(src("styles/control-panel.css"), /\.mgcp-marknoart \{[^}]*dashed/);
});

/* Every line of a .jsx file that is neither inside a /* *​/ block nor a // line. Crude on
   purpose -- these files are plain JSX, and the only thing it is used for below is deciding
   whether a glyph is being RENDERED or merely being written about. */
function codeLines(text) {
  const out = [];
  let inBlock = false;
  text.split("\n").forEach((line, i) => {
    let t = line.trim();
    if (inBlock) {
      const end = t.indexOf("*/");
      if (end === -1) return;
      inBlock = false;
      t = t.slice(end + 2).trim();
    }
    // a comment that opens and does not close on this line
    const open = t.lastIndexOf("/*");
    if (open !== -1 && t.indexOf("*/", open) === -1) {
      inBlock = true;
      t = t.slice(0, open).trim();
    }
    if (t.startsWith("//")) return;
    if (t) out.push([i + 1, t]);
  });
  return out;
}

test("◈ now means Similar, and only Similar, in every string the app renders", () => {
  // The mark for visual similarity since B2 (2026-09-04). The Ledger took the two badges
  // and the mark-button placeholders that were also wearing it; nothing else may. This
  // sweeps every component rather than the four that changed, because the failure it
  // guards against is a NEW ◈ appearing somewhere else and quietly meaning a second thing.
  const files = readdirSync(path.join(SRC, "components"))
    .filter((f) => f.endsWith(".jsx"))
    .map((f) => ["components/" + f, src("components/" + f)]);
  files.push(["App.jsx", app]);

  // The two sites where the mark stands alone, with no word beside it to carry the
  // meaning: the grid tile's hover door and the same door on a Similar result.
  const BARE = new Set(["components/Grid.jsx", "components/SimilarResults.jsx"]);

  const offenders = [];
  for (const [name, text] of files) {
    for (const [n, t] of codeLines(text)) {
      if (!t.includes("◈")) continue;
      if (/similar/i.test(t)) continue;                       // a Similar door or its label
      if (/it\.score/.test(t)) continue;                      // a Similar result's score tip
      if (BARE.has(name) && /^>?◈<?/.test(t.replace(/[\s>]*$/, ""))) continue;
      offenders.push(name + ":" + n + "  " + t);
    }
  }
  assert.deepEqual(offenders, [], "◈ used for something that is not Similar");

  // ...and it is still doing its real job, so this guard cannot pass by deletion.
  assert.match(src("components/Grid.jsx"), /\n\s+◈\n/);
  assert.match(src("components/GridContextMenu.jsx"), /\["◈", "Find similar"/);
  assert.match(details, /<span className="k">◈ SIMILAR<\/span>/);
});
