"""tools/art/build_goal_tiles.py -- Session T (training goal-tile art, issue #61).

The script turns the four owner-picked goal pictures into gallery/src/art/goalTiles.js, the
moon gauge's pattern: base64 WebP data URIs in one generated module, so the art ships in the
app build and the training screen has a picture before any pack is installed. These tests pin
the contract the front end and the maintainer rely on:

  * the four names are GOALS' (gen/trainCore.js), built into the module in GOALS' order;
  * every picture is a TILE_PX square WebP, whatever the source's size or shape;
  * the source folder is an ARGUMENT: the script has no default path to anyone's private
    folder, so nothing private can ride in public code;
  * a folder missing one picture builds nothing (a half module would blank a tile);
  * the committed module is the script's own output shape (header, four exports, TILE_PX).
"""
import base64
import importlib.util
import io
import re
from pathlib import Path

import pytest
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
_TOOL = ROOT / "tools" / "art" / "build_goal_tiles.py"


def _load():
    spec = importlib.util.spec_from_file_location("build_goal_tiles", _TOOL)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _goal_values():
    """GOALS' values, read from the source the app imports (never a second copy here)."""
    src = (ROOT / "gallery" / "src" / "gen" / "trainCore.js").read_text(encoding="utf-8")
    block = src[src.index("export const GOALS"):]
    block = block[:block.index("]);")]
    return re.findall(r'value:\s*"([a-z]+)"', block)


def _write_sources(folder, size=(300, 300), names=None):
    folder.mkdir(parents=True, exist_ok=True)
    for i, name in enumerate(names or ["goal_" + v for v in _goal_values()]):
        Image.new("RGB", size, (40 + 30 * i, 20, 90)).save(folder / (name + ".png"))


def _decode(data_uri):
    head, b64 = data_uri.split(",", 1)
    assert head == "data:image/webp;base64"
    return Image.open(io.BytesIO(base64.b64decode(b64)))


def test_the_tool_exists_and_names_match_goals():
    assert _TOOL.is_file(), "tools/art/build_goal_tiles.py is the Session T build script"
    bgt = _load()
    assert list(bgt.NAMES) == ["goal_" + v for v in _goal_values()]


def test_it_builds_one_square_webp_per_goal_into_the_module(tmp_path):
    bgt = _load()
    src = tmp_path / "src"
    _write_sources(src, size=(1024, 1024))
    out = tmp_path / "goalTiles.js"
    assert bgt.main([str(src), str(out)]) == 0
    text = out.read_text(encoding="utf-8")
    assert text.startswith("// GENERATED by tools/art/build_goal_tiles.py")
    exports = re.findall(r'export const (GOAL_[A-Z_]+|goal_[a-z]+)\b', text)
    assert exports == ["GOAL_TILE_PX"] + ["goal_" + v for v in _goal_values()]
    px = int(re.search(r"export const GOAL_TILE_PX = (\d+);", text).group(1))
    assert px == bgt.TILE_PX
    for v in _goal_values():
        uri = re.search(r'export const goal_%s = "([^"]+)";' % v, text).group(1)
        im = _decode(uri)
        assert im.format == "WEBP" and im.size == (px, px)


def test_a_non_square_source_is_cropped_to_cover_not_stretched(tmp_path):
    """A 2:1 source with a bright left half: a cover crop keeps the centre, so the corner that
    was in the bright half is gone; a stretch would keep both halves."""
    bgt = _load()
    src = tmp_path / "src"
    _write_sources(src)
    wide = Image.new("RGB", (800, 400), (0, 0, 0))
    wide.paste((255, 255, 255), (0, 0, 400, 400))
    wide.save(src / "goal_character.png")
    out = tmp_path / "out.js"
    assert bgt.main([str(src), str(out)]) == 0
    uri = re.search(r'export const goal_character = "([^"]+)";', out.read_text(encoding="utf-8")).group(1)
    im = _decode(uri).convert("RGB")
    # the centre crop of a half-white, half-black picture straddles the seam: left white, right black
    assert im.getpixel((2, im.height // 2))[0] > 200
    assert im.getpixel((im.width - 3, im.height // 2))[0] < 55


def test_a_missing_picture_builds_nothing(tmp_path, capsys):
    bgt = _load()
    src = tmp_path / "src"
    _write_sources(src, names=["goal_character", "goal_style", "goal_clothing"])
    out = tmp_path / "out.js"
    assert bgt.main([str(src), str(out)]) != 0
    assert not out.exists(), "a module with three of four tiles would blank the fourth"
    assert "goal_other" in capsys.readouterr().err


def test_an_unreadable_picture_builds_nothing(tmp_path, capsys):
    bgt = _load()
    src = tmp_path / "src"
    _write_sources(src)
    (src / "goal_style.png").write_bytes(b"not a picture")
    out = tmp_path / "out.js"
    assert bgt.main([str(src), str(out)]) != 0
    assert not out.exists()
    assert "goal_style" in capsys.readouterr().err


def test_the_source_folder_is_an_argument_with_no_default():
    """No path to a private folder in the script: it is required on the command line."""
    text = _TOOL.read_text(encoding="utf-8")
    assert ("moonglade" + "-internal") not in text
    assert "handoff" not in text.lower()
    bgt = _load()
    with pytest.raises(SystemExit):
        bgt.main([])


def test_the_committed_module_has_the_scripts_shape():
    mod = ROOT / "gallery" / "src" / "art" / "goalTiles.js"
    assert mod.is_file(), "gallery/src/art/goalTiles.js is the script's committed output"
    text = mod.read_text(encoding="utf-8")
    assert text.startswith("// GENERATED by tools/art/build_goal_tiles.py")
    assert ("moonglade" + "-internal") not in text
    names = re.findall(r"export const (goal_[a-z]+) =", text)
    assert names == ["goal_" + v for v in _goal_values()]
    px = int(re.search(r"export const GOAL_TILE_PX = (\d+);", text).group(1))
    for v in _goal_values():
        uri = re.search(r'export const goal_%s = "([^"]+)";' % v, text).group(1)
        im = _decode(uri)
        assert im.size == (px, px)


# ---- the pack's own copy (precedence: pack, then module, then tint) --------------------------

def test_a_pack_copy_under_training_is_served_and_its_absence_is_a_plain_404(tmp_path):
    """The front end asks /branding/training/goal_<goal>.png first (lib/goalTileCore.js). When
    the pack carries it the route serves it; when it does not the answer is a 404, which is what
    sends the tile on to the app's own module copy. Pack v7 only has to carry the files, in the
    training role's coded folder (ROLE_CODE["training"]), where the public name now lands."""
    import moonglade_gallery as g
    from moonglade_gallery import CATALOG_FIELDS, save_catalog
    from tests.conftest import login_client
    save_catalog(tmp_path / "catalog.db", [
        {f: "" for f in CATALOG_FIELDS} | {"media_id": "1", "filename": "a.png",
                                           "created_at": "2025-01-01T00:00:00"}])
    cli = login_client(tmp_path)
    assert cli.get("/branding/training/goal_character.png").status_code == 404
    pack = g._role_dir("training")
    pack.mkdir(parents=True)
    Image.new("RGB", (8, 8), (1, 2, 3)).save(pack / "goal_character.png")
    r = cli.get("/branding/training/goal_character.png")
    assert r.status_code == 200 and r.mimetype == "image/png"
