"""tools/art/build_inbox_icon.py -- the ✉ Inbox button's mailbox (owner's art, 2026-10-04).

The script turns the owner's mailbox picture into gallery/src/art/inboxIcon.js, the goal tiles'
pattern (tools/art/build_goal_tiles.py): one WebP data URI in a generated module, so the inbox
button has its picture before any pack carries it. These tests pin the contract:

  * the picture is an ICON_PX square WebP that keeps its transparency, whatever the source's size;
  * a source that is not square is fitted inside the square, never stretched or cropped;
  * the source picture is an ARGUMENT: the script has no default path to anyone's private folder;
  * a missing or unreadable source builds nothing;
  * the committed module is the script's own output shape, and a valid WebP data URI with alpha;
  * the pack's own copy is asked for at /branding/rewards/inbox.png: served when the pack has
    it, a plain 404 when not (which sends the button on to the module's copy).
"""
import base64
import importlib.util
import io
import re
from pathlib import Path

import pytest
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
_TOOL = ROOT / "tools" / "art" / "build_inbox_icon.py"
_MODULE = ROOT / "gallery" / "src" / "art" / "inboxIcon.js"


def _load():
    spec = importlib.util.spec_from_file_location("build_inbox_icon", _TOOL)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _decode(data_uri):
    head, b64 = data_uri.split(",", 1)
    assert head == "data:image/webp;base64"
    im = Image.open(io.BytesIO(base64.b64decode(b64)))
    im.load()
    return im


def _uri(text):
    return re.search(r'export const inbox_icon = "([^"]+)";', text).group(1)


def _source(path, size=(992, 992)):
    """A transparent square with an opaque disc in the middle: a stand-in for the mailbox."""
    im = Image.new("RGBA", size, (0, 0, 0, 0))
    w, h = size
    r = min(w, h) // 3
    for x in range(w // 2 - r, w // 2 + r):
        for y in range(h // 2 - r, h // 2 + r):
            if (x - w // 2) ** 2 + (y - h // 2) ** 2 <= r * r:
                im.putpixel((x, y), (200, 120, 60, 255))
    im.save(path)
    return path


def test_it_builds_one_square_webp_with_alpha_into_the_module(tmp_path, capsys):
    bii = _load()
    out = tmp_path / "inboxIcon.js"
    assert bii.main([str(_source(tmp_path / "mailbox.png", (240, 240))), str(out)]) == 0
    text = out.read_text(encoding="utf-8")
    assert text.startswith("// GENERATED by tools/art/build_inbox_icon.py")
    assert re.findall(r"export const (\w+)\b", text) == ["INBOX_ICON_PX", "inbox_icon"]
    px = int(re.search(r"export const INBOX_ICON_PX = (\d+);", text).group(1))
    assert px == bii.ICON_PX == 96, "sharp at 3x and more for the largest place it is drawn (22 px in the header)"
    im = _decode(_uri(text))
    assert im.format == "WEBP" and im.size == (px, px)
    assert im.mode == "RGBA"
    a = im.getchannel("A")
    assert a.getpixel((0, 0)) == 0, "the corners stay transparent"
    assert a.getpixel((px // 2, px // 2)) > 250, "the picture stays opaque"
    assert "bytes" in capsys.readouterr().out, "the build reports its size"


def test_a_non_square_source_is_fitted_not_stretched(tmp_path):
    """A 2:1 source with a centred disc: fitted, the disc stays round (as wide as it is tall);
    a stretch would make it twice as wide as tall."""
    bii = _load()
    out = tmp_path / "out.js"
    assert bii.main([str(_source(tmp_path / "wide.png", (400, 200))), str(out)]) == 0
    a = _decode(_uri(out.read_text(encoding="utf-8"))).getchannel("A")
    box = a.point(lambda v: 255 if v > 128 else 0).getbbox()
    w, h = box[2] - box[0], box[3] - box[1]
    assert abs(w - h) <= 2, box


@pytest.mark.parametrize("bad", ["missing", "unreadable"])
def test_a_missing_or_unreadable_source_builds_nothing(tmp_path, capsys, bad):
    bii = _load()
    src = tmp_path / "mailbox.png"
    if bad == "unreadable":
        src.write_bytes(b"not a picture")
    out = tmp_path / "out.js"
    assert bii.main([str(src), str(out)]) != 0
    assert not out.exists()
    assert "mailbox.png" in capsys.readouterr().err


def test_the_source_is_an_argument_with_no_default():
    """No path to a private folder in the script: the picture is required on the command line."""
    text = _TOOL.read_text(encoding="utf-8")
    assert ("moonglade" + "-internal") not in text
    assert "handoff" not in text.lower()
    with pytest.raises(SystemExit):
        _load().main([])


def test_the_committed_module_is_the_scripts_output_and_a_valid_webp_with_alpha():
    assert _MODULE.is_file(), "gallery/src/art/inboxIcon.js is the script's committed output"
    text = _MODULE.read_text(encoding="utf-8")
    assert text.startswith("// GENERATED by tools/art/build_inbox_icon.py")
    assert ("moonglade" + "-internal") not in text
    px = int(re.search(r"export const INBOX_ICON_PX = (\d+);", text).group(1))
    im = _decode(_uri(text))
    assert im.format == "WEBP" and im.size == (px, px) and im.mode == "RGBA"
    lo, hi = im.getchannel("A").getextrema()
    assert lo == 0 and hi == 255, "a transparent ground around an opaque mailbox"


def test_a_pack_copy_under_rewards_is_served_and_its_absence_is_a_plain_404(tmp_path):
    """The button asks /branding/rewards/inbox.png first. When the pack carries it the route
    serves it -- it is chrome, like gift.png, so the rewards seal leaves it open -- and when it
    does not the answer is a 404, which sends the button on to the module's copy. Pack v7 only
    has to carry the file, at the rewards role's coded folder."""
    import moonglade_gallery as g
    from moonglade_gallery import CATALOG_FIELDS, save_catalog
    from tests.conftest import login_client
    save_catalog(tmp_path / "catalog.db", [
        {f: "" for f in CATALOG_FIELDS} | {"media_id": "1", "filename": "a.png",
                                           "created_at": "2025-01-01T00:00:00"}])
    cli = login_client(tmp_path)
    assert cli.get("/branding/rewards/inbox.png").status_code == 404
    pack = g._role_dir("rewards")
    pack.mkdir(parents=True, exist_ok=True)
    Image.new("RGBA", (8, 8), (1, 2, 3, 255)).save(pack / "inbox.png")
    r = cli.get("/branding/rewards/inbox.png")
    assert r.status_code == 200 and r.mimetype == "image/png"
