#!/usr/bin/env python3
"""Build the training goal tiles' art (Session T, issue #61) into gallery/src/art/goalTiles.js.

    python dev/tools/art/build_goal_tiles.py <folder holding goal_*.png> [out.js]

The folder is an ARGUMENT, never a default: it holds the four 1024-px pictures the owner chose
for Basic training's goal tiles, and where they live on any machine is that machine's business.
`out.js` defaults to gallery/src/art/goalTiles.js in this checkout.

WHAT IT MAKES
One WebP per goal, TILE_PX px square, written as base64 data URIs into one JS module -- the moon
gauge's pattern (art/moonGauge.js): the pictures ship in the app build, so the training screen
has art before any pack is installed, and the pack's own copy (training/goal_*.png, pack v7)
wins whenever it is there. The module is committed; this script is how it is regenerated.

The names are gen/trainCore.js's GOALS values behind a goal_ prefix, in GOALS' order:
goal_character, goal_style, goal_clothing, goal_other.

SIZE
The desktop tile's picture is about 130 css px across at a 1400 px window (four tiles in a row
inside the Train card) and the phone row's is 44. TILE_PX = 288 is 2.2x the desktop picture, so it
stays sharp on a 2x screen, and 6.5x the phone row's (3x phones included): one file serves both.
Quality 86 at method 6 keeps each picture to a few tens of KB.

A source that is not square is cropped to cover (centred), never stretched. A missing or
unreadable picture stops the build with a message naming it and writes nothing: a module with
three of the four would blank the fourth tile.

Static files only: no network. Pillow.
"""
import argparse
import base64
import io
import sys
from pathlib import Path

from PIL import Image, ImageOps

# gen/trainCore.js GOALS' values, in its order (dev/tests/test_build_goal_tiles.py reads that file
# and fails if these ever drift from it).
GOAL_VALUES = ("character", "style", "clothing", "other")
NAMES = tuple("goal_" + v for v in GOAL_VALUES)
TILE_PX = 288
QUALITY = 86

HEADER = (
    "// GENERATED by dev/tools/art/build_goal_tiles.py -- do not edit by hand.\n"
    "// Basic training's four goal pictures (Session T): one %d px square WebP each, as data URIs,\n"
    "// named for gen/trainCore.js GOALS. The pack's training/goal_*.png wins when it is installed;\n"
    "// these are the fallback behind it (components/train/GoalTile.jsx). Regenerate with the script.\n"
) % TILE_PX


def _tile_uri(path):
    with Image.open(path) as im:
        im.load()
        rgb = im.convert("RGB")
    sq = ImageOps.fit(rgb, (TILE_PX, TILE_PX), Image.LANCZOS, centering=(0.5, 0.5))
    buf = io.BytesIO()
    sq.save(buf, "WEBP", quality=QUALITY, method=6)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def build(folder):
    """The module text for the four pictures in `folder`. Raises ValueError, naming the
    picture, when one is missing or will not open."""
    folder = Path(folder)
    uris = {}
    for name in NAMES:
        path = folder / (name + ".png")
        if not path.is_file():
            raise ValueError("%s.png is not in %s" % (name, folder))
        try:
            uris[name] = _tile_uri(path)
        except Exception as exc:                       # an unreadable or truncated file
            raise ValueError("%s.png could not be read (%s)" % (name, type(exc).__name__))
    lines = [HEADER, "export const GOAL_TILE_PX = %d;\n" % TILE_PX]
    lines += ['export const %s = "%s";\n' % (name, uris[name]) for name in NAMES]
    return "".join(lines)


def default_out():
    return Path(__file__).resolve().parents[3] / "gallery" / "src" / "art" / "goalTiles.js"


def main(argv=None):
    ap = argparse.ArgumentParser(description="Build gallery/src/art/goalTiles.js from the goal pictures.")
    ap.add_argument("folder", help="the folder holding goal_character.png, goal_style.png, "
                                   "goal_clothing.png and goal_other.png")
    ap.add_argument("out", nargs="?", default=None, help="the module to write (default: this "
                    "checkout's gallery/src/art/goalTiles.js)")
    args = ap.parse_args(argv)
    try:
        text = build(args.folder)
    except ValueError as exc:
        print("build_goal_tiles: " + str(exc), file=sys.stderr)
        return 1
    out = Path(args.out) if args.out else default_out()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    print("Wrote %s (%d bytes, %d px tiles)" % (out, out.stat().st_size, TILE_PX))
    return 0


if __name__ == "__main__":
    sys.exit(main())
