#!/usr/bin/env python3
"""Build the ✉ Inbox button's mailbox (owner's art, 2026-10-04) into gallery/src/art/inboxIcon.js.

    python tools/art/build_inbox_icon.py <source picture> [out.js]

The source picture is an ARGUMENT, never a default: it is the owner's transparent mailbox, and
where it lives on any machine is that machine's business. `out.js` defaults to
gallery/src/art/inboxIcon.js in this checkout.

WHAT IT MAKES
One square WebP that keeps its transparency, written as a base64 data URI into one JS module --
the goal tiles' pattern (tools/art/build_goal_tiles.py): the picture ships in the app build, so the
inbox button has its mailbox before any pack is installed, and the pack's own copy
(rewards/inbox.png, pack v7) wins whenever it is there. The module is committed; this script is
how it is regenerated.

SIZE
The largest place the mailbox is drawn is the header's 30 px button, at 22 px (the gift box's own
size for gift.png); the phone's Menu row draws it at 18 px. ICON_PX = 96 is over 4x the header's
22 px, so it stays sharp on a 3x screen. Quality 90 at method 6, alpha kept lossless, holds the
module to a few KB.

A source that is not square is fitted inside the square (centred, on a transparent ground), never
stretched or cropped. A missing or unreadable picture stops the build with a message naming it
and writes nothing.

Static files only: no network. Pillow.
"""
import argparse
import base64
import io
import sys
from pathlib import Path

from PIL import Image

ICON_PX = 96
QUALITY = 90

HEADER = (
    "// GENERATED by tools/art/build_inbox_icon.py -- do not edit by hand.\n"
    "// The ✉ Inbox button's mailbox (owner's art, 2026-10-04): one %d px square WebP with alpha, as a\n"
    "// data URI. The pack's rewards/inbox.png wins when it is installed; this is the fallback behind it,\n"
    "// and the ✉ glyph behind that (inbox/InboxIcon.jsx). Regenerate with the script.\n"
) % ICON_PX


def _icon_uri(path):
    with Image.open(path) as im:
        im.load()
        rgba = im.convert("RGBA")
    w, h = rgba.size
    scale = ICON_PX / max(w, h)
    fit = rgba.resize((max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS)
    sq = Image.new("RGBA", (ICON_PX, ICON_PX), (0, 0, 0, 0))
    sq.paste(fit, ((ICON_PX - fit.width) // 2, (ICON_PX - fit.height) // 2))
    buf = io.BytesIO()
    sq.save(buf, "WEBP", quality=QUALITY, method=6, alpha_quality=100)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def build(source):
    """The module text for the picture at `source`. Raises ValueError, naming the picture,
    when it is missing or will not open."""
    source = Path(source)
    if not source.is_file():
        raise ValueError("%s is not there" % source)
    try:
        uri = _icon_uri(source)
    except Exception as exc:                           # an unreadable or truncated file
        raise ValueError("%s could not be read (%s)" % (source, type(exc).__name__))
    return "".join([HEADER, "export const INBOX_ICON_PX = %d;\n" % ICON_PX,
                    'export const inbox_icon = "%s";\n' % uri])


def default_out():
    return Path(__file__).resolve().parents[2] / "gallery" / "src" / "art" / "inboxIcon.js"


def main(argv=None):
    ap = argparse.ArgumentParser(description="Build gallery/src/art/inboxIcon.js from the mailbox picture.")
    ap.add_argument("source", help="the mailbox picture (a transparent PNG or WebP)")
    ap.add_argument("out", nargs="?", default=None, help="the module to write (default: this "
                    "checkout's gallery/src/art/inboxIcon.js)")
    args = ap.parse_args(argv)
    try:
        text = build(args.source)
    except ValueError as exc:
        print("build_inbox_icon: " + str(exc), file=sys.stderr)
        return 1
    out = Path(args.out) if args.out else default_out()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    print("Wrote %s (%d bytes, a %d px icon)" % (out, out.stat().st_size, ICON_PX))
    return 0


if __name__ == "__main__":
    sys.exit(main())
