"""Generate gallery/src/icons/Icons.jsx from the SVG files beside it.

The seven icons are the owner's Glyph Ledger picks (moonglade-internal/design/glyphs/
README.md, 2026-09-05), drawn by the Glyphs set (glyphs.fyi, MIT -- see the NOTICE file
in gallery/src/icons/). The .svg files in gallery/src/icons/ are the SHIPPED assets and
the source of truth; this script transcribes them into one React module so they render
INLINE -- no runtime fetch, no icon font, no sprite sheet -- and so `color:` tints them.

Why generated rather than hand-copied: the same reason static/design-tokens.css is
(tools/export_design_kit.py + tests/test_design_kit_sync.py). A second copy of anything
drifts unless a test pins it to its source; tests/test_icons_sync.py runs this generator
and fails if the committed module is stale, naming the command that repairs it.

TWO EDITS ARE MADE TO THE DRAWN ART, both mechanical and both listed here so nobody has
to diff the files against the private originals to find them:

  1. `#C2CCDE` -> `currentColor`. Every ballot icon draws in that one hardcoded hex; the
     duo variants make their second tone from the SAME hex at fill-opacity .25, so the
     swap carries the two-tone for free. This is what makes a skin retint its own icons.
     laptop-cog_poly is the exception: it is POLYchrome (#4F4F4F body, #BB6BD9 deck,
     #6FCF97 cog) and has no #C2CCDE at all, so it is mapped onto the same duo grammar --
     body at .25, deck and cog at full. See POLY_MAP.

  2. `vector-effect="non-scaling-stroke"` on the HAIRLINE strokes -- and only those. The
     duo art is drawn on an 80x80 canvas with the default stroke-width of 1; these icons
     render at 9-20px in this app, where that hairline scales to a fifth of a pixel and
     the icon collapses to its 25% ghost fill. Measured in driven Chromium before the
     change: at 10/13/16px "as drawn" reads as a smudge, non-scaling-stroke reads as the
     drawn icon. At the art's own 80px size the two are identical (1 user unit = 1px
     there), so this preserves the drawing at its native size rather than reweighting it.
     A path that carries its OWN stroke-width is left alone -- person-private_bold's
     stroke-width="6" is a drawn weight meant to scale, and pinning it to 6 device pixels
     would swallow the icon at every size the app actually uses it.

Run:  python tools/build_icons.py        (writes gallery/src/icons/Icons.jsx)
"""
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
ICON_DIR = REPO / "gallery" / "src" / "icons"
OUT = ICON_DIR / "Icons.jsx"

# app meaning -> the drawn file. The file names are the Glyphs set's own, kept verbatim so
# the provenance survives; the keys are what the app calls them.
ICONS = [
    ("search", "binoculars-1_bold", "Search — every search surface (owner: \"All search surfaces\")"),
    ("uses", "person-private_bold", "The model picker's \"N uses\""),
    ("lora", "palette_duo", "My Art's USER LORA badge"),
    ("entered", "check-badge_duo", "A contest this library has entries in"),
    ("snippets", "quote_duo", "The composer's saved-prompt snippets"),
    ("folio", "trophy_duo", "The Folio of Honors"),
    ("panel", "laptop-cog_poly", "The Control Panel"),
]

TINT = "#C2CCDE"
# laptop-cog_poly's three drawn tones -> the duo grammar (see the header note).
POLY_MAP = [
    ('fill="#4F4F4F"', 'fill="currentColor" fill-opacity="0.25"'),
    ('fill="#BB6BD9"', 'fill="currentColor"'),
    ('fill="#6FCF97"', 'fill="currentColor"'),
]

# SVG attribute -> its JSX spelling. Anything not listed is passed through unchanged,
# which is correct for the plain ones (d, fill, stroke, opacity...).
JSX_ATTR = {
    "fill-rule": "fillRule",
    "clip-rule": "clipRule",
    "fill-opacity": "fillOpacity",
    "stroke-opacity": "strokeOpacity",
    "stroke-width": "strokeWidth",
    "stroke-linecap": "strokeLinecap",
    "stroke-linejoin": "strokeLinejoin",
    "stroke-dasharray": "strokeDasharray",
    "vector-effect": "vectorEffect",
    "clip-path": "clipPath",
}

HEAD = '''/* GENERATED by tools/build_icons.py from the .svg files beside this one -- DO NOT
   HAND-EDIT. Edit the .svg, then re-run:  python tools/build_icons.py
   (tests/test_icons_sync.py fails if this file is stale.)

   THE OWNER'S GLYPH LEDGER, drawn (moonglade-internal/design/glyphs/README.md,
   2026-09-05). Seven icons from the Glyphs set -- glyphs.fyi, MIT, credited in the
   NOTICE file beside these -- replacing seven Unicode stand-ins.

   HOW THEY TINT, and why there is no icon font. Each icon draws in `currentColor`, so
   `color:` paints it: every skin retints its own icons, a hover state retints on hover,
   and a disabled control dims with its own text. The duo icons get their second tone
   from the same colour at fill-opacity .25, so that comes free. Nothing is fetched at
   runtime -- these are React elements in the bundle, like NavSpine's gear and
   SeparatorBar's chevron before them.

   SIZE IS TYPE-RELATIVE. The default is 1em, so an icon grows and shrinks with the text
   it sits beside; a caller that needs a different ratio passes `size` ("1.15em", 16).
   Sites that want one ratio for a whole class of chrome set it in CSS instead
   (gallery/src/styles/icons.css). */
import React from "react";
import "../styles/icons.css";

'''

TAIL = '''
/* One icon. `title` makes it an announced image; without one it is decorative and
   hidden from the a11y tree, which is right wherever the label beside it already says
   the word. */
export default function Icon({ name, size = "1em", title, className, style }) {
  const glyph = GLYPHS[name];
  if (!glyph) return null;
  return (
    <svg
      className={"mgico" + (className ? " " + className : "")}
      viewBox="0 0 80 80"
      width={size}
      height={size}
      fill="none"
      style={style}
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : "true"}
      focusable="false"
    >
      {title ? <title>{title}</title> : null}
      {glyph}
    </svg>
  );
}

export const ICON_NAMES = Object.keys(GLYPHS);
'''


def transform(text, poly):
    """The .svg on disk -> the .svg this repo ships. Idempotent."""
    if poly:
        for old, new in POLY_MAP:
            text = text.replace(old, new)
    else:
        text = text.replace(TINT, "currentColor")
    # A DEFAULT-WIDTH stroke at this canvas size needs a device-constant stroke; a path
    # with its own stroke-width keeps it (header note 2).
    def fix(m):
        el = m.group(0)
        if "vector-effect" in el or "stroke-width" in el:
            return el
        return el.replace('stroke="currentColor"',
                          'stroke="currentColor" vector-effect="non-scaling-stroke"', 1)

    text = re.sub(r"<\w+[^>]*stroke=\"currentColor\"[^>]*/>", fix, text)
    return text


def inner(text):
    """The children of <svg>, whitespace as authored."""
    body = text.split(">", 1)[1].rsplit("</svg>", 1)[0]
    return body.strip("\n")


def to_jsx(body, indent="    "):
    """Element source -> JSX source. These files are flat lists of <path .../>, so a
    tag-level rewrite is enough -- and if a future icon brings a nested element, the
    assertion below stops it silently rendering wrong."""
    out = []
    for m in re.finditer(r"<(\w+)((?:\s+[\w:-]+=\"[^\"]*\")*)\s*/>", body):
        tag, attrs = m.group(1), m.group(2)
        assert tag in ("path", "circle", "rect", "ellipse", "line", "polygon", "polyline"), tag
        pairs = re.findall(r'([\w:-]+)="([^"]*)"', attrs)
        rendered = " ".join(
            '%s="%s"' % (JSX_ATTR.get(k, k), v) for k, v in pairs if k != "xmlns"
        )
        out.append("%s<%s %s />" % (indent, tag, rendered))
    # every element accounted for: no silent drop
    assert len(out) == body.count("<"), (len(out), body.count("<"))
    return "\n".join(out)


def build():
    blocks = []
    for key, fname, note in ICONS:
        path = ICON_DIR / (fname + ".svg")
        raw = path.read_text(encoding="utf-8")
        want = transform(raw, poly=fname.endswith("_poly"))
        if want != raw:
            path.write_text(want, encoding="utf-8", newline="\n")
            raw = want
        blocks.append(
            "  /* %s -- %s.svg */\n  %s: (\n    <>\n%s\n    </>\n  ),"
            % (note, fname, key, to_jsx(inner(raw), indent="      "))
        )
    return HEAD + "const GLYPHS = {\n" + "\n".join(blocks) + "\n};\n" + TAIL


def main():
    text = build()
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote", OUT.relative_to(REPO))
    return 0


if __name__ == "__main__":
    sys.exit(main())
